In [5]:

def get_bounds(data):
  """Return bounds of data."""
  min_x = 0
  max_x = 0
  min_y = 0
  max_y = 0

  abs_x = 0
  abs_y = 0
  for i in range(len(data)):
    x = float(data[i, 0])
    y = float(data[i, 1])
    abs_x += x
    abs_y += y
    min_x = min(min_x, abs_x)
    min_y = min(min_y, abs_y)
    max_x = max(max_x, abs_x)
    max_y = max(max_y, abs_y)

  return (min_x, max_x, min_y, max_y)

In [7]:
import numpy as np
## Some sample code for loading the dataset

## For the seq data

bear_seq = np.load("dataset/seq/sketchrnn_bear.npz", allow_pickle=True, encoding="latin1")

bear_seq_train = bear_seq["train"]
bear_seq_test = bear_seq["test"]
bear_seq_valid = bear_seq["valid"]

print(get_bounds(bear_seq_train[0]))
print(bear_seq_train[0])

(-31.0, 102.0, -17.0, 116.0)
[[ 43   0   0]
 [  8   6   1]
 [  6   1   0]
 [  1 -10   0]
 [ 11 -11   0]
 [  7  -3   0]
 [ 13   0   0]
 [  6   3   0]
 [  7  22   0]
 [ -3   6   0]
 [-27  20   1]
 [-72 -37   0]
 [ -1  -7   0]
 [-15  -2   0]
 [-13   5   0]
 [ -2   6   0]
 [  7  26   0]
 [ 12   9   1]
 [ 41  11   0]
 [ -6   1   0]
 [ -5   7   0]
 [ -2  13   0]
 [  3   7   0]
 [  7   5   0]
 [ 11   1   0]
 [  5  -5   0]
 [ -1 -25   0]
 [-11  -3   0]
 [ -9   3   0]
 [-12  10   1]
 [-14 -19   0]
 [ -6  30   0]
 [  0  21   0]
 [  3   6   0]
 [ 20  16   0]
 [  8   3   0]
 [ 37   0   0]
 [  8  -2   0]
 [ 11 -14   0]
 [  6 -25   0]
 [ -5 -33   0]
 [ -3  -6   0]
 [ -7  -4   1]
 [-51   5   0]
 [  0   0   1]
 [ -4  -6   0]
 [  2   5   1]]
